apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.chatbot.nfs.pvcName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.chatbot.nfs.size }}
  storageClassName: nfs-storage
  volumeName: {{ .Values.chatbot.nfs.volumeName }}
